### ISSUE TITLE
droonga-engineのinstall.shを使ったインストール方法

### ISSUE THREAD

**Issue by long-long-float** [droonga/droonga.org#17]
``` sh
$ curl https://raw.githubusercontent.com/droonga/droonga-engine/master/script/install.sh | sudo bash
```

**Comment by long-long-float** [comment]
サービスの起動と終了

### debian

```
$ sudo service droonga-engine start #起動
$ sudo service droonga-engine stop #終了
```

### CentOS

```
# /sbin/service droonga-engine start #起動
# /sbin/service droonga-engine stop #終了
```

**Comment by piroor** [comment]
I've changed the location of the installation script.

Install a release version:

```
curl https://raw.githubusercontent.com/droonga/droonga-engine/master/install.sh | sudo bash
```

Install the latest revision from the repository:

```
curl https://raw.githubusercontent.com/droonga/droonga-engine/master/install.sh | sudo INSTALL_VERSION=master bash
```

**Comment by kou** [comment]
> ```
> curl https://raw.githubusercontent.com/droonga/droonga-engine/master/install.sh | sudo INSTALL_VERSION=master bash
> ```

How about `VERSION=master` instead of `INSTALL_VERSION=master`?
The script is install script. So we may omit `INSTALL_` prefix.

**Comment by piroor** [comment]
You are totally right... I've removed the prefix. Thanks.

**Comment by piroor** [comment]
Updated steps to install:

Install a release version:

```
curl https://raw.githubusercontent.com/droonga/droonga-engine/master/install.sh | sudo bash
curl https://raw.githubusercontent.com/droonga/droonga-http-server/master/install.sh | sudo bash
```

Install the latest revision from the repository:

```
curl https://raw.githubusercontent.com/droonga/droonga-engine/master/install.sh | sudo VERSION=master bash
curl https://raw.githubusercontent.com/droonga/droonga-droonga-http-server/master/install.sh | sudo VERSION=master bash
```

**Comment by piroor** [comment]
Next, I have to update steps to setup droonga-(engine|http-server).yaml and catalog.json. Now they are placed under the home directory of each user...

**Comment by piroor** [comment]
Done.
