### ISSUE TITLE
v1.1.2 directory

### ISSUE THREAD

**Issue by KitaitiMakoto** [droonga/droonga.org#18]
Hi,

I found some typos and obsolete descriptions in tutorial. I want to send pull requests to fix them but I don't know how generate directory for new version. Could you tell me how or generate it?

Thank you.

**Comment by kou** [comment]
Thanks!

You can generate files for new version by the following command:

``` text
% rake release NEW_VERSION=1.1.2
```

**Comment by KitaitiMakoto** [comment]
Thanks! I did it!
